nelmio_api_doc:
    documentation:
        info:
            title: Pokemonstore
            description: API for Pokemonstore
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api/(?!doc$).*
